security:
  basic:
    enabled: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

hystrix:
  metrics:
    enabled: false
server:
  port: 7001

management:
  security.enabled: false
  trace.include: parameters,errors

ribbon.eureka.enabled: false
account-service.ribbon.listOfServers: localhost:7000