security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: local
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
server:
  port: 8001

AUTH_SERVER: https://pivot-aparthasarathy.login.run.pcfbeta.io/

security:
  basic:
    enabled: false
  require_ssl: false

---

spring:
  profiles: sso
  cloud:
    config:
      enabled: true

security:
  oauth2:
    client:
      client-id: f17dfc29-7c0f-4e50-af2c-06a21b670fd0
      client-secret: 7c7aafa6-18ff-4d37-9e20-3a7dd34d975a
    resource:
      preferTokenInfo: false
      userInfoUri: ${AUTH_SERVER}/userinfo
      tokenInfoUri: ${AUTH_SERVER}/check_token
      jwk:
        key-set-uri: ${AUTH_SERVER}/token_keys

hystrix.command.default.execution.isolation.strategy: SEMAPHORE