spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

server:
  port: 7001

management:
  endpoints:
    enabled-by-default: true
  endpoint:
    httptrace:
      enabled: true

account-service.ribbon.listOfServers: localhost:7000