security:
  basic:
    enabled: false

spring:
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

hystrix:
  metrics:
    enabled: false
server:
  port: 7000

management:
  security.enabled: false
  trace.include: parameters,errors
