security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: local
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
server:
  port: 8001

---

spring:
  profiles: sso
  cloud:
    config:
      enabled: true
eureka:
  client:
    enabled: false

